
int setEveryFourthBitTo1();
int test_setEveryFourthBitTo1();
int anyOddBitIs1();
int test_anyOddBitIs1();
int everyEvenBitIs0();
int test_everyEvenBitIs0();
int replaceByteN(int, int, int);
int test_replaceByteN(int, int, int);
int countBits(int);
int test_countBits(int);
int logicalNot(int);
int test_logicalNot(int);
int isTMax(int);
int test_isTMax(int);
int fitsInShort(int);
int test_fitsInShort(int);
int determineSign(int);
int test_determineSign(int);
int multiplyByThreeEighths(int);
int test_multiplyByThreeEighths(int);
int isPowerOfTwo(int);
int test_isPowerOfTwo(int);
unsigned floatIsInfinity(unsigned);
unsigned test_floatIsInfinity(unsigned);
unsigned floatIsNaN(unsigned);
unsigned test_floatIsNaN(unsigned);
unsigned floatAbsoluteValue(unsigned);
unsigned test_floatAbsoluteValue(unsigned);
unsigned floatNegate(unsigned);
unsigned test_floatNegate(unsigned);
unsigned floatMultiplyByTwo(unsigned);
unsigned test_floatMultiplyByTwo(unsigned);
int floatToInteger(unsigned);
int test_floatToInteger(unsigned);
